application: poke150returnstest01
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /pdf/(.*)
  static_files: pdf/\1
  upload: pdf/(.*)

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest